# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kristopher Micinski
email: kris@cs.haverford.edu
description: > # this means to ignore newlines until "baseurl:"
   Kris Micinski's personal website. Visiting CS Prof at Haverford.
baseurl: "http://kmicinski.com" #"http://localhost:4000/"
url: "http://kmicinski.com"  #"http://localhost:4000/"  #"http://kmicinski.com" 
twitter_username: krismicinski
github_username:  kmicinski
permalink: pretty

# Build settings
#markdown: redcarpet

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
